# Generated by Django 2.1 on 2019-08-15 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejemploapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='detalleprestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroejemplar', models.CharField(max_length=45)),
                ('fechadecompra', models.CharField(max_length=45)),
                ('id_Libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejemploapp.Libro')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaprestamo', models.CharField(max_length=45)),
                ('nombrecliente', models.CharField(max_length=45)),
                ('telefonocliente', models.CharField(max_length=45)),
                ('estado', models.BooleanField(default=True, editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='detalleprestamo',
            name='id_ejemplar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejemploapp.Ejemplar'),
        ),
        migrations.AddField(
            model_name='detalleprestamo',
            name='id_prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejemploapp.Prestamo'),
        ),
    ]
