# Generated by Django 2.1 on 2019-08-15 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemploapp', '0002_auto_20190815_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleprestamo',
            old_name='id_ejemplar',
            new_name='ejemplar',
        ),
        migrations.RenameField(
            model_name='detalleprestamo',
            old_name='id_prestamo',
            new_name='prestamo',
        ),
        migrations.RenameField(
            model_name='ejemplar',
            old_name='id_Libro',
            new_name='Libro',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='nombrecliente',
            new_name='nombre_cliente',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='telefonocliente',
            new_name='telefono_cliente',
        ),
    ]
