# Generated by Django 2.1 on 2019-08-15 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemploapp', '0003_auto_20190815_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ejemplar',
            old_name='numeroejemplar',
            new_name='numero_ejemplar',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='fechaprestamo',
            new_name='fecha_prestamo',
        ),
    ]
