# Generated by Django 2.1 on 2019-08-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemploapp', '0004_auto_20190815_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejemplar',
            name='fechadecompra',
        ),
        migrations.AddField(
            model_name='ejemplar',
            name='fecha_de_compra',
            field=models.DateField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='copias',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateField(max_length=45),
        ),
    ]
